/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace Iridescent.Entities
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Category : DomainObject 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private int _id; 
		
		// Properties 
		private string _name; 
		private int _diarycount; 
		private DateTime _createdate; 
		private bool _isenabled; 		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Category()
		{
			_id = 0; 
			_name = null; 
			_diarycount = 0; 
			_createdate = DateTime.MinValue; 
			_isenabled = false; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Category(int id, string name, int diarycount, DateTime createdate, bool isenabled)
		{
			_id = id; 
			_name = name; 
			_diarycount = diarycount; 
			_createdate = createdate; 
			_isenabled = isenabled; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual int Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual string Name
		{
			get { return _name; }
			set	
			{
				if ( value != null )
					if( value.Length > 50)
						throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());
				
				_isChanged |= (_name != value); _name = value;
			}
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual int DiaryCount
		{
			get { return _diarycount; }
			set { _isChanged |= (_diarycount != value); _diarycount = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual DateTime CreateDate
		{
			get { return _createdate; }
			set { _isChanged |= (_createdate != value); _createdate = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual bool IsEnabled
		{
			get { return _isenabled; }
			set { _isChanged |= (_isenabled != value); _isenabled = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}